function [ Node, LocX, LocY, LocZ, UXm, UYm, UZm, SEQVNm2] = importPostProcessData( filename )
    %UNTITLED3 Summary of this function goes here
    %   Detailed explanation goes here

    %% Import data from text file.
    % Script for importing data from the following text file:
    %
    %    O:\Afstuderen\Ansys\_AnsysModelWorkingDirectory\20190411_HDPE_static\202_HDPE_reinforced\202_HDPE_reinforced_RailfootRotation_R_4.csv
    %
    % To extend the code to different selected data or a different text file,
    % generate a function instead of a script.

    % Auto-generated by MATLAB on 2019/04/12 16:11:10

    %% Initialize variables.
    delimiter = ';';
    startRow = 2;

    %% Format string for each line of text:
    %   column1: double (%f)
    %	column2: double (%f)
    %   column3: double (%f)
    %	column4: double (%f)
    %   column5: double (%f)
    %	column6: double (%f)
    %   column7: double (%f)
    %	column8: double (%f)
    %   column9: double (%f)
    %	column10: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

    filename
    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    %% Allocate imported array to column variable names
    Node = dataArray{:, 1};
    LocX = dataArray{:, 2};
    LocY = dataArray{:, 3};
    LocZ = dataArray{:, 4};
    UXm = dataArray{:, 5};
    UYm = dataArray{:, 6};
    UZm = dataArray{:, 7};
    SEQVNm2 = dataArray{:, 8};
    EQVtotalstrain = dataArray{:, 9};
    EQVelasticstrain = dataArray{:, 10};

    %% Clear temporary variables
    clearvars filename delimiter startRow formatSpec fileID dataArray ans;

end

