!Save pictures of elements (a picture per material).



/VIEW,1,1,2,3   
/ANG,1
ESEL, S, MAT, , Staal
EPLOT
/AUTO,1 
/REP,FAST  
*USE, '%MacroFolder(1)%save_plot.MAC', 'ElementsStaal'
ESEL, S, MAT, , Materiaal_S
EPLOT
/AUTO,1 
/REP,FAST  
*USE, '%MacroFolder(1)%save_plot.MAC', 'ElementsKunststof'
ESEL, ALL
ESEL, U, MAT, , Materiaal_S
ESEL, U, MAT, , Staal
EPLOT
/AUTO,1 
/REP,FAST  
*USE, '%MacroFolder(1)%save_plot.MAC', '_ElementsOverig'



