basefolder = 'O:/Afstuderen/Ansys/_AnsysModelWorkingDirectory/';

%% Input:

analysisfolder = '20201015_static_AnalysisLojda';
LoadCases = [1;2;3;4;5;6;7];
outputfolder = strcat('O:/Afstuderen/DataAnalyse/MatlabPostProcess/Results/', analysisfolder, ' - ', date, '/');

%% Call Post processing script:

    while 1 %While loop to be able to collapse code
        % Add that folder plus all subfolders to the path.
        addpath(genpath(pwd))
        mkdir(outputfolder)
        
        outputfolder_copiedFiles = strcat(outputfolder, 'Copied_files/');
        mkdir(outputfolder_copiedFiles);
        
        resultsfolder = strcat(basefolder, analysisfolder, '/'); %Where to find results
        
        
        folders = GetSubDirs(resultsfolder); %Get all the individual analysis folders by name
        for n = 1:length(folders)
            filenames_to_copy = { ...
                '*ReactionForcesPerSleeper*'; ...
                '*GaugeNodes*'; ...
                '*.png'; ...
                '*Foundationdeformations*'; ...
                '*MaxStresses*'; ...
            }';

            for m = 1:length(filenames_to_copy)    
                file_to_copy = strcat(resultsfolder, folders(n).name, '/', filenames_to_copy(m));
                
                

               [status,message,messageId] = copyfile(file_to_copy{1}, outputfolder_copiedFiles);        
            end
        end

    
        %% analysis names:
        
%        analysis_names_general_multiple = { ...
%             '202_HDPE_Multiple_Static'; ...
%             '201_PE_Multiple_Static';...
%         }';
        analysis_names_general_multiple = {};

%         analysis_names_simple = { ...
%             %'202_HDPE_Simple_1Div'; ...
%             %'202_HDPE_Simple_2DIV'; ...
%             %'202_HDPE_Simple_3Div';...
%             %'202_HDPE_Simple_4Div';...
%             %'202_HDPE_Simple_5Div';... %Did not solve
%             %'202_HDPE_Simple_6Div'...
%         };

        %% 2 Div analysis
        analysis_names_general = { ...
            '201_PE_Simple_2DIV'; ...
            '201_PE_2DIV';...
            '202_HDPE_Simple_2DIV'; ...
            '202_HDPE_2DIV'; ...
            '202_Hout_2Div'; ...
            '202_Beton_2Div'; ...
        }';
    
        analysis_names_simple = { ...
            '202_HDPE_Simple_2DIV'; ...
        };
        analysis_names_standard = {...
            '202_HDPE_2Div'; ...
        };
    
        analysis_names_201 = { ...
            '201_PE_Simple_2DIV'; ...
            '201_PE_2DIV';...
        };

        analysis_names_202 = {...
            '202_HDPE_Simple_2DIV'; ...
            '202_HDPE_2DIV'; ...
            '202_Hout_2Div'; ...
            '202_Beton_2Div'; ...
        };

        
        %% 3 Div analysis 
        
%         analysis_names_general = { ...
%             '201_PE_Simple_3DIV'; ...
%             '201_PE_3DIV';...
%             '202_HDPE_Simple_3DIV'; ...
%             '202_HDPE_3DIV'; ...
%             '202_Hout_3Div'; ...
%             '202_Beton_3Div'; ...
%         }';

%         analysis_names_standard = {...
%             %'202_HDPE_1Div'; ...
%             %'202_HDPE_2Div'; ...
%             '202_HDPE_3Div'; ...
%             %'202_HDPE_4Div' ....
%         };
%         analysis_names_simple = { ...
%             '202_HDPE_Simple_3DIV'; ...
%         };
%         analysis_names_201 = { ...
%             '201_PE_Simple_3DIV'; ...
%             '201_PE_3DIV';...
%         };
% 
%         analysis_names_202 = {...
%             '202_HDPE_Simple_3DIV'; ...
%             '202_HDPE_3DIV'; ...
%             '202_Hout_3Div'; ...
%             '202_Beton_3Div'; ...
%         };
    break
    end
    

    %% Run function with parameters:
    PostProcess( ...
        analysisfolder,...
        LoadCases, ...
        outputfolder, ...
        analysis_names_general, ...
        analysis_names_general_multiple,...
        analysis_names_simple, ...
        analysis_names_standard, ...
        analysis_names_201, ...
        analysis_names_202 ...
    );

%% 
% basefolder = 'O:/Afstuderen/Ansys/_AnsysModelWorkingDirectory/';
% resultsFolder = strcat(basefolder, analysisfolder, '/'); %Where to find results
% 
%     for index = 1:length(LoadCases);    
%        PP_saveMaximumStressesPerSleeperType(strcat(resultsFolder, '%s/%s_', 'Foundationdeformations', '_', num2str(LoadCases(index)) ,'_Stresses.csv'), analysis_names_201, analysis_names_202, outputfolder, num2str(LoadCases(index)));
%     end 